### ISSUE TITLE
zca_switch_lists_states:38: bad set of key/value pairs for associative array

### ISSUE THREAD

**Issue by matejcik** [psprint/zsh-cmd-architect#1]
with zsh 5.3 on openSUSE x86_64, the above error happens whenever I press `<tab>` twice, i.e., going to the command window and back. Also when doing pretty much anything in the command window.

Commenting out line 38 in `zca` seems to fix the problem with no ill effects.

**Comment by psprint** [comment]
I've commited a fix for this. Thanks.
